### ISSUE TITLE
Support Docker Registry API v2

### ISSUE THREAD

**Issue by yoshiotu** [banyanops/collector#5]

**Comment by justingood** [comment]
This would be great. I've just learned about this project, but we've already switched to v2, so can't use it :cry: 

Docker is still [working on](https://github.com/docker/distribution/issues/206) search & indexing for v2, so that feature won't work until they enable it. For the time being, the /v2 endpoint still allows for grabbing info about specific repositories.

**Comment by yoshiotu** [comment]
Thanks for your comment! This is high on the priority list for sure.

**Comment by yoshiotu** [comment]
Collector now has initial support for v2. You need to give --registryproto=v2 and you also need to specify individual repositories. Tested using the registry:2.0 container, with no TLS and no authentication (--registryhttps=false and --registryauth=false). It should also work with TLS and Basic Auth.

Please let me know if there are any problems, or if other registry configurations would be useful to support.

**Comment by justingood** [comment]
Working well for me!

**Comment by yoshiotu** [comment]
Glad to hear it.
